% SPDBSCAN SuperPixel DBSCAN clustering for image segmentation
%用于图像分割的SPDBSCAN SuperPixel DBSCAN聚类
% Usage:  [lc, C, regionsC] = spdbscan(l, Cp, Am, E)
%
% Arguments:  (Note this code is structured assuming the input superpixels
%              have been generated using SLIC) 注意，假设使用SLIC生成输入超像素，则构造此代码
%       l   - Labeled image of clusters/regions generated by a superpixel
%             algorithm,  such as  SLIC.     l-由超像素产生的簇/区域的标记图像算法，例如SLIC
%       Cp  - 5 x Np array, as returned by SLIC. Each column giving the     SLIC返回的5 x Np数组。 
%             attributes of each superpixel region.  Only the first 3  每列给出每个超像素区域的属性。
%             attributes, the Lab colour values, are used.  仅使用前3个属性（Lab颜色值）。
%       Am  - An adjacency matrix of the labeled image (also returned by SLIC).标记图像的邻接矩阵（也由SLIC返回）。
%       E   - Matching tolerance value/distance threshold that controls which匹配容差值/距离阈值  
%             superpixels are clustered together.  This value is in L*a*b*，用于控制哪些超像素聚集在一起。
%             colour units.  Try a value in the range 5-10 to start with.该值为L* a* b*颜色单位。
%             Changing the value of E by just 1 unit can give a significant尝试在5-10范围内的值开始。
%             difference. 将E的值仅改变1个单位可以产生显着差异。
%
% Returns:
%        lc - New labeled image corresponding to the new clustered regions of
%             superpixels.新标记的图像对应于新的超像素聚集区域。
%         C - Cell array of length Nc listing indices of superpixel regions长度为Nc的
%             associated with each cluster.单元阵列列出了与每个簇相关联的超像素区域的索引。
%  regionsC - Array of length Np listing the cluster number associated with
%             each superpixel region.  列出与每个超像素区域相关联的簇编号的长度Np的阵列。
%
% This function performs an image segmentation using the DBSCAN algorithm to 该功能使用DBSCAN算法执行  
% form clusters of superpixels.  In determining the neighbourhood of any 图像分割以形成超像素的簇。
% superpixel the following criterion is used: If any two superpixels are 在确定任何超像素的邻域时，使用以下标准：
% adjacent the clustering distance measure is the lab colour distance between 如果任何两个超像素相邻，则聚类距离度量
% the colour centres of the two superpixels.  If any two superpixels are not 是两个超像素的色心之间的lab颜色距离。
% adjacent the clustering distance measure is assumed infinite.  The use of an 如果任何两个超像素不相邻，
% adjacency matrix allows the DBSCAN scan algorithm to be efficient in 则聚类距离度量被假设为无穷大。
% determining the neighbourhood of each superpixel. 邻接矩阵的使用允许DBSCAN扫描算法在确定每个超像素的邻域方面是有效的。
%
% See also: SLIC, REGIONADJACENCY, DBSCAN, DRAWREGIONBOUNDARIES

% DBSCAN Reference: 
% Martin Ester, Hans-Peter Kriegel, J鰎g Sander, Xiaowei Xu (1996). "A
% density-based algorithm for discovering clusters in large spatial databases
% with noise".  Proceedings of the Second International Conference on Knowledge
% Discovery and Data Mining (KDD-96). AAAI Press. pp. 226-231.  
% Also see: http://en.wikipedia.org/wiki/DBSCAN

% Copyright (c) 2013 Peter Kovesi
% www.peterkovesi.com/matlabfns/
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in 
% all copies or substantial portions of the Software.
%
% The Software is provided "as is", without warranty of any kind.

% ** To Do: Make the distance measure incorporate some measure of any edge **待办事项：使距离测量包含任何
% continuity that adjacent superpixels might have     **边缘的一些度量相邻超像素可能具有的连续性**
% ** Allow attributes other than Lab colour to be used **    **允许使用Lab颜色以外的属性**

% March 2013
% July  2013  Changes to accommondate superpixel attributes being passed as a
%             struct array

function [lc, C, regionsC] = spdbscan(l, Sp, Am, Ec, gray, E3)
    
    minPts = 1;  
    Np = length(Sp);
    
    regionsC  = zeros(Np,1);
    C     = {};%cell结构
    Nc    = 0;               % Cluster counter.
    Pvisit = zeros(Np,1);    % Array to keep track of superpixels that have
                             % been visited.   用于跟踪已访问过的超像素的数组。
                             
    % Determine the regionQuery function to use depending on the field names
    % of the struct array Sp  根据struct array Sp的字段名确定要使用的regionQuery函数
    fn = fieldnames(Sp);%Sp各个量的名字
    if strcmp(fn{1}, 'L')                % Lab colour space
        regionQuery = @regionQueryM;
    elseif strcmp(fn{1}, 'value')        % Euclidean distance欧氏距离
        regionQuery = @regionQueryE;
    else
        error(['Unable to determine region query function to use with the super' ...
               ' pixel data'])%'无法确定要与超级''像素数据'一起使用的区域查询功能
    end
                             
    for n = 1:Np

       if ~Pvisit(n)                  % If this superpixel not visited yet...如果这个超级像素还没有访问过......
           Pvisit(n) = 1;                          % mark it as visited将其标记为已访问
           neighbours = regionQuery(Sp, Am, n, Ec, gray, E3); % and find its neighbours并找到其邻居
           % Form a cluster...
           Nc = Nc + 1;      % Increment number of clusters and process
                             % neighbourhood.增加集群数和进程邻域数。
                           
           C{Nc} = [n];      % Initialise cluster Nc with point n  使用点n初始化集群Nc
           regionsC(n) = Nc; % and mark superpixel n as being a member of cluster Nc.并将超像素n标记为簇Nc的成员。
               
           ind = 1;          % Initialise index into neighbourPts array.将索引初始化为neighbourPts数组。
               
           % For each superpixel Sp' in list of neighbours ...对于邻居列表中的每个超像素Sp'...
           while ind <= length(neighbours)
               
               nb = neighbours(ind);
               
               if ~Pvisit(nb)        % If this neighbour has not been visited如果没有访问该邻居
                   Pvisit(nb) = 1;   % mark it as visited.将其标记为已访问。
                   
                   % Find the neighbours of this neighbour and 
                   % add them to the neighbours list找到该邻居的邻居并将其添加到邻居列表中
                   neighboursP = regionQuery(Sp, Am, nb, Ec, gray, E3);
                   neighbours = [neighbours  neighboursP];
               end            
               
               % If this neighbour nb not yet a member of any cluster add it
               % to this cluster.  如果此邻居nb尚未成为任何群集的成员，则将其添加到此群集。
               if ~regionsC(nb)  
                   C{Nc} = [C{Nc} nb];
                   regionsC(nb) = Nc;
               end
               
               ind = ind + 1;  % Increment neighbour point index and process
                               % next neighbour  增加邻居点索引并处理下一个邻居
           end

       end
    end
    
    % Generate new labeled image corresponding to the new clustered regions生成与新聚集区域对应的新标记图像
    lc = zeros(size(l));
    for n = 1:length(regionsC)
        lc(l==n) = regionsC(n);
    end

        
    
% %------------------------------------------------------------------------
% % Find indices of all superpixels adjacent to superpixel n with mean colour
% % difference less than Ec.  Use CMC colour difference measure
% %   找到与超像素n相邻的所有超像素的索引，其平均色差小于Ec。 使用CMC色差测量
% % Arguments:
% %             Sp - The struct array of superpixel attributes 超像素属性的struct数组
% %             An - Adjacency matrix 邻接矩阵
% %              n - Index of superpixel being considered 正在考虑超像素的索引
% %             Ec - Colour distance threshold 色彩距离阈值
% 
% function neighbours = regionQueryCMC(Sp, Am, n, Ec)
%     
%     lw = 1;
%     neighbours = [];
%     
%     % Get indices of all superpixels connected to superpixel n  获取连接到超像素n的所有超像素的索引
%     ind = find(Am(n,:));
%     
%     for i = ind
%         
%         dE = cmcdifference([Sp(i).L; Sp(i).a; Sp(i).b],...
%                            [Sp(n).L; Sp(n).a; Sp(n).b], lw);
%         
%         if dE < Ec
%             neighbours = [neighbours i];     
%         end
%     end
% 
%     
% %------------------------------------------------------------------------
% % Find indices of all superpixels adjacent to superpixel n with mean Lab 
% % colour difference less than Ec. 查找与超像素n相邻的所有超像素的索引，其中Lab色差小于Ec。
% %
% % Arguments:
% %             Sp - The struct array of superpixel attributes超像素属性的struct数组
% %             An - Adjacency matrix邻接矩阵
% %              n - Index of point of interest正在考虑超像素的索引
% %             Ec - Colour distance threshold色彩距离阈值
% 
% function neighbours = regionQueryM(Sp, Am, n, Ec)
%     
%     E2 = Ec^2;   
%     neighbours = [];
%     
%     % Get indices of all superpixels connected to superpixel n  获取连接到超像素n的所有超像素的索引
%     ind = find(Am(n,:));
%     
%     for i = ind
%         % Test if distance^2 < E^2 
%         v = [Sp(i).L; Sp(i).a; Sp(i).b] - ...
%             [Sp(n).L; Sp(n).a; Sp(n).b];
% 
%         dist2 = v'*v;
%         if dist2 < E2 
%             neighbours = [neighbours i];     
%         end
%     end
% 
%     
% %------------------------------------------------------------------------
% % Find indices of all superpixels adjacent to superpixel n with mean 
% % Euclidean colour difference less than Ec.找到与超像素n相邻的所有超像素的指数，其中平均欧几里德色差小于Ec。
% %
% % Arguments:
% %             Sp - The struct array of superpixel attributes超像素属性的struct数组
% %             An - Adjacency matrix邻接矩阵
% %              n - Index of point of interest正在考虑超像素的索引
% %             Ec - Colour distance threshold色彩距离阈值
% 
% function neighbours = regionQueryE(Sp, Am, n, Ec)
%     
%     E2 = Ec^2;   
%     neighbours = [];
%     
%     % Get indices of all superpixels connected to superpixel n  获取连接到超像素n的所有超像素的索引
%     ind = find(Am(n,:));
%     
%     for i = ind
%         % Test if distance^2 < E^2 
%         v = Sp(i).value - Sp(n).value;
% 
%         if v'*v < E2 
%             neighbours = [neighbours i];     
%         end
%     end
%     
%     